name: Deploy
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Sync to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - run: aws s3 sync _site s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude "*README.md"
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
